modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="extendedmushrooms"
version="${file.jarVersion}"
displayName="Extended Mushrooms"
displayURL="https://www.curseforge.com/minecraft/mc-mods/extended-mushrooms"
authors="Cech12"
description='''
This mod changes some mushroom behaviour and adds mushroom related blocks, items and recipes.
'''